### ISSUE TITLE
Develop draft of content for intermediary homepage

### ISSUE THREAD

**Issue by leahbannon** [18F/fec-alpha#24]

**Comment by emileighoutlaw** [comment]
**Dependencies:** 
- Content strategy 
- Homepage content decisions with relevant team members

**Goal:** a quick blurb on what this issue is trying to accomplish

**Completion Criteria:** Team reviews and approves

**Tasks to completion:**
- [ ] Collect all related, current web copy into one document
- [ ] Restructure, condense, and revise for new format
- [ ] Ensure plain language is centerpiece of content's design

**Comment by emileighoutlaw** [comment]
Has been completed and implemented!
