### ISSUE TITLE
Content change management + strategy

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-alpha#46]
https://docs.google.com/document/d/14ZyfNSXrsrmj-SoiZwYZCHfp6Dx3Hm4sd1YPXnI2gKA/edit

**Goal:** Develop a strategy for managing FEC content (moving forward) and making revisions to current site content with Jeremy.

**Completion Criteria:** Team reviews and approves

**Tasks to completion:**
- [ ] Interviews with relevant content folks (research)
- [ ] Flesh out content change management document
- [ ] Plan for implementation of plan

**Comment by leahbannon** [comment]
I think we've accomplished most of this, except for planning for sustainability. Is that a fair assessment? Perhaps we can postpone figuring that part out until September? What do you all think?

**Comment by emileighoutlaw** [comment]
I agree we should postpone, at least until we've gotten a fair amount of content truly approved (e.g., OGC and Commissioner). That will be important for our change management.

**Comment by noahmanger** [comment]
This is captured on the story map so closing out here.
