### ISSUE TITLE
Define options for main image on beta home page

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-alpha#59]
**Goal:** Provide a menu of imagery options for FEC to choose from that keep the aesthetic goals of the site, while finding the right mix of content focus. Do this to help select the image that will be used. 

**Tasks to completion:**
- [ ] Come up with 5-7 alternative images
- [ ] Gather feedback by sending to slack before next design meeting, review at weekly design meeting 
- [ ] Select image to use

**Comment by jenniferthibault** [comment]
Moving to post-launch backlog in favor of transition page.
