### ISSUE TITLE
Revise icon designs

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-alpha#60]
**Goal:** Complete changes to icons that will create the full set of icons we need for the existing pages

**Tasks to Completion:**
- [x] Using feedback form 8/17 Design Review meeting, redesign the following icons:
  - [x] Candidate
  - [x] Committees
  - [x] Receipts 
- [x] Review by sending to slack before next design meeting
- [x] Update style guide
