### ISSUE TITLE
Checklist Content

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-alpha#61]
Link to Google doc: https://docs.google.com/document/d/1bIePrNHy4mE1HlxdoakG5yoKibvaRa4afupYgZC0A3g/edit

**Tasks to Completion:**
- [x] Generate content
- [x] Edit with design team 
- [x] Submit to Amy and Amy for final review
- [x] Implement Amys' edits
- [x] Final copy editing read-through

**Comment by emileighoutlaw** [comment]
Complete.
