### ISSUE TITLE
Essentials (Knowledge Center) Content 

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-alpha#62]
Link to Google doc: https://docs.google.com/document/d/1XcTXPJ9e2T-vnys1wXNQRvhKMRuAGsPfCZ7lVy3KS8o/edit

**Tasks to Completion:**
- [x] Generate content
- [x] Submit to Amy and Amy initial review
- [x] Implement edits
- [x] Submit to Amy and Amy for final review
- [x] Implement Amys' edits
- [x] Final copy editing read-through 
- [x] Submit to design team

**Fully approved**
- [x] Get an e-filing password
- [x] Register with the FEC
- [x] Get a treasurer
- [x] Get electronic filing software
- [x] Administrative fines
- [x] Get a tax ID
- [x] Get a bank account
- [x] Test the waters
- [x] Know your filing requirements
- [x] Mandatory electronic filing
- [x] File electronically
- [x] File by paper
- [x] Amend a report
- [x] Learn more about quarterly reports
- [x] Learn more about pre-election reports
- [x] Learn more about 48-Hour Notices
- [x] Post-general election reports
- [x] Terminate your committee
- [x] Request for Additional Information (RFAI)
- [x] Contact us
- [x] Missed deadline

**Comment by leahbannon** [comment]
wow look at all those check boxes :)

**Comment by emileighoutlaw** [comment]
Complete.
