### ISSUE TITLE
Registration Options Content

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-alpha#63]
Link to Google doc: https://docs.google.com/document/d/1VyeKEBxB4nfkg822g2wmjowJW4g8Vy7YD79n1w47zQQ/edit

**Tasks to Completion:**
- [x] Generate content
- [x] Edit with design team
- [x] Submit to Amy and Amy for final review
- [x] Implement Amys' edits
- [x] Final copy editing read-through

**Comment by emileighoutlaw** [comment]
Complete.
