### ISSUE TITLE
Registration and Reporting Content

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-alpha#64]
Link to Google doc: https://docs.google.com/document/d/1_T-wahGbdlJO9lpzeqYsSA7r5J81Y-A9V394n0KPxao/edit

**Tasks to Completion:**
- [x] Generate content
- [x] Review with design team
- [x] Submit to Amy and Amy for final review
- [x] Implement Amys' edits
- [x] Final copy editing read-through

**Comment by emileighoutlaw** [comment]
Complete.
